export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; auth_user_id: string | null; username: string | null; name: string; phone: string; email: string | null; hire_date: string; status: "active" | "disabled"; system_role: "admin" | "user"; created_at: string; updated_at: string }; Insert: { id?: string; auth_user_id?: string | null; username?: string | null; name: string; phone?: string; email?: string | null; hire_date: string; status?: "active" | "disabled"; system_role?: "admin" | "user"; created_at?: string; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>; Relationships: [] };
      positions: { Row: { id: number; code: string; name: string; default_permissions: string[]; created_at: string }; Insert: { code: string; name: string; default_permissions?: string[]; created_at?: string }; Update: { code?: string; name?: string; default_permissions?: string[] }; Relationships: [] };
      user_positions: { Row: { profile_id: string; position_id: number; created_at: string }; Insert: { profile_id: string; position_id: number; created_at?: string }; Update: { profile_id?: string; position_id?: number; created_at?: string }; Relationships: [{ foreignKeyName: "user_positions_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }, { foreignKeyName: "user_positions_position_id_fkey"; columns: ["position_id"]; isOneToOne: false; referencedRelation: "positions"; referencedColumns: ["id"] }] };
      performance_records: { Row: { id: string; profile_id: string; host_profile_id: string | null; month: string; revenue_cents: number; status: "draft" | "pending" | "approved" | "rejected"; reject_reason: string | null; submitted_at: string | null; reviewed_at: string | null; reviewed_by: string | null; created_at: string; updated_at: string }; Insert: { id?: string; profile_id: string; host_profile_id?: string | null; month: string; revenue_cents: number; status?: "draft" | "pending" | "approved" | "rejected"; reject_reason?: string | null; submitted_at?: string | null; reviewed_at?: string | null; reviewed_by?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["performance_records"]["Insert"]>; Relationships: [] };
      salary_schemes: { Row: { id: string; profile_id: string | null; position_id: number | null; name: string; version: number; base_salary_cents: number; guaranteed_salary_cents: number; threshold_multiplier_bps: number; commission_rate_bps: number; effective_from: string; status: "active" | "archived"; created_at: string }; Insert: { id?: string; profile_id?: string | null; position_id?: number | null; name: string; version: number; base_salary_cents: number; guaranteed_salary_cents: number; threshold_multiplier_bps?: number; commission_rate_bps: number; effective_from: string; status?: "active" | "archived"; created_at?: string }; Update: Partial<Database["public"]["Tables"]["salary_schemes"]["Insert"]>; Relationships: [] };
      teams: { Row: { id: string; name: string; host_profile_id: string; status: "active" | "disabled"; created_at: string; updated_at: string }; Insert: { id?: string; name: string; host_profile_id: string; status?: "active" | "disabled"; created_at?: string; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["teams"]["Insert"]>; Relationships: [{ foreignKeyName: "teams_host_profile_id_fkey"; columns: ["host_profile_id"]; isOneToOne: true; referencedRelation: "profiles"; referencedColumns: ["id"] }] };
      team_members: { Row: { team_id: string; profile_id: string; created_at: string }; Insert: { team_id: string; profile_id: string; created_at?: string }; Update: Partial<Database["public"]["Tables"]["team_members"]["Insert"]>; Relationships: [{ foreignKeyName: "team_members_team_id_fkey"; columns: ["team_id"]; isOneToOne: false; referencedRelation: "teams"; referencedColumns: ["id"] }, { foreignKeyName: "team_members_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: true; referencedRelation: "profiles"; referencedColumns: ["id"] }] };
      salary_records: { Row: { id: string; profile_id: string; position_id: number; scheme_id: string | null; month: string; revenue_cents: number; tenure_month: number; threshold_cents: number; is_qualified: boolean; is_grace_period: boolean; guaranteed_component_cents: number; performance_component_cents: number; gross_cents: number; service_fee_cents: number; net_cents: number; commission_rate_bps: number; status: "draft" | "confirmed" | "published" | "voided"; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["salary_records"]["Row"], "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["salary_records"]["Insert"]>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: { current_profile_id: { Args: Record<PropertyKey, never>; Returns: string }; is_admin: { Args: Record<PropertyKey, never>; Returns: boolean } };
    Enums: { employment_status: "active" | "disabled"; performance_status: "draft" | "pending" | "approved" | "rejected"; salary_record_status: "draft" | "confirmed" | "published" | "voided"; scheme_status: "active" | "archived"; system_role: "admin" | "user" };
    CompositeTypes: Record<string, never>;
  };
};
